# Use root/example as user/password credentials
# sudo docker compose -f anotation-backend-dockercompose.yml up -d
# to build
# sudo docker build --tag 'anotaion-tool-backend' .
version: '1.1'
networks:
  anotation-tool-net:
    external: true
services:
  mongo:
    image: mongo
    container_name: mongo-pritesh
    restart: always
    networks:
      - anotation-tool-net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
     - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  anotaion-tool-backend:
    build: .
    image: anotaion-tool-backend-docker-image
    container_name: anotaion-tool-backend
    restart: always
    networks:
      - anotation-tool-net
    ports:
      - 8083:8083
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
      MONGODB_DB : DevDB
      MONGODB_DATAONE : hello
      MONGODB_DATATWO : hello2
      TAG : v1.6
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2g
        reservations:
          cpus: '1.0'
          memory: 1g
volumes:
 mongo-data:
  driver: local